# ??? ?? ???? ???? 5~6?? ?? ????? ?? ?? ? ??? 8081 , 8001 ... ? ????? ?? ?????
server:
  port: 0

spring:
  application:
    name: 2nd-service

eureka:
  # ?? ??? ???? Eureka Server UI ?? ?? ?? ???? ??? id ??
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}
  client:
    # Eureka Server ?? Service Registry ? ????? ??
    fetch-registry: true
    # Eureka Server ?? ?? ????? ????? ??
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

