# Eureka Server Port (default)
server:
  port: 8761

# Eureka Sever? ????? Server
# Server? ???? ?? ?? register-with-eureka: false
# ?? ???? ????? ???? ???? ?? ??? fetch-register: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
